BEGIN TRAN
BEGIN

    /* 주의!!! 5.고객사별 모듈정의 확인 필요! */
    /* 주의!!! 5.고객사별 모듈정의 확인 필요! */
    /* 주의!!! 5.고객사별 모듈정의 확인 필요! */
    /* 주의!!! 5.고객사별 모듈정의 확인 필요! */
    /* 주의!!! 5.고객사별 모듈정의 확인 필요! */

    DECLARE        @OLD_COMP        NVARCHAR(10)
                 , @NEW_COMP        NVARCHAR(10)
				 , @NEW_COMP_NAME	NVARCHAR(40)

    SET @OLD_COMP = 'MASTER'
    SET @NEW_COMP = 'UBONE'					-- SaaS 멀티 법인코드 정의
	SET @NEW_COMP_NAME = 'UB-ONE Co.,LTD.'		-- 고객사 영문명 정의



    DELETE FROM BSA400T WHERE COMP_CODE = @NEW_COMP
    DELETE FROM BSA210T WHERE COMP_CODE = @NEW_COMP

	DELETE FROM BSA110T WHERE COMP_CODE = @NEW_COMP

    DELETE FROM BSA100T WHERE COMP_CODE = @NEW_COMP

    DELETE FROM BOR120T WHERE COMP_CODE = @NEW_COMP
    DELETE FROM BOR100T WHERE COMP_CODE = @NEW_COMP


--  1. 법인추가
    INSERT INTO BOR100T(COMP_CODE, COMP_NAME, COMP_ENG_NAME, REPRE_NAME, REPRE_ENG_NAME, REPRE_NO, COMPANY_NUM, COMP_OWN_NO, COMP_KIND, COMP_CLASS
                      , COMP_TYPE, SESSION, FN_DATE, TO_DATE, ESTABLISH_DATE, CAPITAL, ZIP_CODE, ADDR, ENG_ADDR, TELEPHON, FAX_NUM, HTTP_ADDR, EMAIL
                      , DOMAIN, PL_BASE, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER, INSERT_DB_TIME)
    SELECT @NEW_COMP, @NEW_COMP_NAME AS COMP_NAME, @NEW_COMP_NAME AS COMP_ENG_NAME, REPRE_NAME, REPRE_ENG_NAME, REPRE_NO, COMPANY_NUM, COMP_OWN_NO, COMP_KIND, COMP_CLASS
                      , COMP_TYPE, SESSION, FN_DATE, TO_DATE, ESTABLISH_DATE, CAPITAL, ZIP_CODE, ADDR, ENG_ADDR, TELEPHON, FAX_NUM, HTTP_ADDR, EMAIL
                      , DOMAIN, PL_BASE, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER, INSERT_DB_TIME
    FROM   BOR100T WITH (NOLOCK)
    WHERE  COMP_CODE = @OLD_COMP

--  2. 사업장 추가
    INSERT INTO BOR120T(COMP_CODE, DIV_CODE, DIV_NAME, COMPANY_NUM, REPRE_NAME, REPRE_NO, COMP_CLASS, COMP_TYPE, ZIP_CODE, ADDR, TELEPHON, FAX_NUM, SAFFER_TAX
                      , SAFFER_TAX_NM, BILL_DIV_CODE, TAX_NAME, TAX_NUM, TAX_TEL, HANDPHONE, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, DIV_FULL_NAME
                      , EMAIL, INSERT_DB_USER, INSERT_DB_TIME)
    SELECT @NEW_COMP, DIV_CODE, DIV_NAME, COMPANY_NUM, REPRE_NAME, REPRE_NO, COMP_CLASS, COMP_TYPE, ZIP_CODE, ADDR, TELEPHON, FAX_NUM, SAFFER_TAX
         , SAFFER_TAX_NM, BILL_DIV_CODE, TAX_NAME, TAX_NUM, TAX_TEL, HANDPHONE, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, DIV_FULL_NAME
         , EMAIL, INSERT_DB_USER, INSERT_DB_TIME
    FROM   BOR120T WITH (NOLOCK)
    WHERE  COMP_CODE = @OLD_COMP
    AND    DIV_CODE  = '01'

--  3. 부서 추가
	INSERT INTO BSA210T (COMP_CODE, TREE_CODE, TREE_NAME, TYPE_LEVEL, SECTION_CD, USE_YN, MAKE_SALE, COST_KIND
					, SORT_SEQ, REMARK, TREE_LEVEL, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03
					, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER, INSERT_DB_TIME)
	SELECT @NEW_COMP, TREE_CODE, @NEW_COMP, TYPE_LEVEL, SECTION_CD, USE_YN, MAKE_SALE, COST_KIND
					, SORT_SEQ, REMARK, TREE_LEVEL, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03
					, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER, INSERT_DB_TIME
	FROM BSA210T WITH (NOLOCK)
	WHERE COMP_CODE = @OLD_COMP

--  4. 업무별숫자포멧정보 추가
	INSERT INTO BSA110T (COMP_CODE, JOB_CODE, FORMAT_QTY, FORMAT_PRICE, FORMAT_IN, FORMAT_OUT, FORMAT_QTY2, FORMAT_PRICE2
		, FORMAT_IN2, FORMAT_OUT2, FORMAT_RATE, FORMAT_RATE2, FORMAT_QTY_T, FORMAT_PRICE_T, FORMAT_IN_T, FORMAT_OUT_T
		, FORMAT_RATE_T, FORMAT_QTY2_T, FORMAT_PRICE2_T, FORMAT_IN2_T, FORMAT_OUT2_T, FORMAT_RATE2_T, UPDATE_DB_USER
		, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER, INSERT_DB_TIME)
	SELECT @NEW_COMP, JOB_CODE, FORMAT_QTY, FORMAT_PRICE, FORMAT_IN, FORMAT_OUT, FORMAT_QTY2, FORMAT_PRICE2
		, FORMAT_IN2, FORMAT_OUT2, FORMAT_RATE, FORMAT_RATE2, FORMAT_QTY_T, FORMAT_PRICE_T, FORMAT_IN_T, FORMAT_OUT_T
		, FORMAT_RATE_T, FORMAT_QTY2_T, FORMAT_PRICE2_T, FORMAT_IN2_T, FORMAT_OUT2_T, FORMAT_RATE2_T, UPDATE_DB_USER
		, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER, INSERT_DB_TIME
	FROM BSA110T WITH (NOLOCK)
	WHERE COMP_CODE = @OLD_COMP

--  5. 프로그램 정보(★★★★ 고객사별 모듈 정의 ★★★★)
	INSERT INTO BSA400T(COMP_CODE, PGM_SEQ, PGM_ID, PGM_TYPE, PGM_LEVEL, UP_PGM_DIV, PGM_ARNG_SEQ, PGM_NAME, PGM_NAME_EN
					, PGM_NAME_CN, PGM_NAME_JP, LOCATION, TYPE, USE_YN, AUTHO_TYPE, AUTHO_PGM, PGMMER, PGM_DATE, UPDATE_MAN
					, UPDATE_DATE, REMARK, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER
					, INSERT_DB_TIME)
	SELECT @NEW_COMP, PGM_SEQ, PGM_ID, PGM_TYPE, PGM_LEVEL, UP_PGM_DIV, PGM_ARNG_SEQ, PGM_NAME, PGM_NAME_EN
		 , PGM_NAME_CN, PGM_NAME_JP, LOCATION, TYPE, USE_YN, AUTHO_TYPE, AUTHO_PGM, PGMMER, PGM_DATE, UPDATE_MAN
		 , UPDATE_DATE, REMARK, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER
		 , INSERT_DB_TIME
 	FROM BSA400T WITH (NOLOCK)
	WHERE COMP_CODE = @OLD_COMP
--		AND PGM_SEQ IN ('11','12','13','14','15','16','18','19','21','32') -- [전체] 11:기준정보, 12:인사/급여관리, 13:회계관리, 14:영업관리, 15:생산관리, 16:구매/자재, 18:재고관리, 19:무역관리, 21:원가관리, 32:장비관리
		AND PGM_SEQ IN ('11','12','13') -- [일반]관리 


--  9. 종합코드 추가
    INSERT INTO BSA100T(COMP_CODE, MAIN_CODE, SUB_CODE, CODE_NAME, CODE_NAME_EN, CODE_NAME_CN, CODE_NAME_JP, SYSTEM_CODE_YN, REF_CODE1, REF_CODE2, REF_CODE3
                      , REF_CODE4, REF_CODE5, USE_YN, SORT_SEQ, SUB_LENGTH, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
                      , INSERT_DB_USER, INSERT_DB_TIME)
    SELECT @NEW_COMP, MAIN_CODE, SUB_CODE, CODE_NAME, CODE_NAME_EN, CODE_NAME_CN, CODE_NAME_JP, SYSTEM_CODE_YN, REF_CODE1, REF_CODE2, REF_CODE3
         , REF_CODE4, REF_CODE5, USE_YN, SORT_SEQ, SUB_LENGTH, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
         , INSERT_DB_USER, INSERT_DB_TIME
    FROM   BSA100T WITH (NOLOCK)
    WHERE  COMP_CODE = @OLD_COMP


/* ---------------------------------------------------------------------------------------
-- 회계
----------------------------------------------------------------------------------------*/
--/*
	DELETE FROM ABA100T	WHERE COMP_CODE = @NEW_COMP			--2.  회계기준설정
	DELETE FROM ABA120T	WHERE COMP_CODE = @NEW_COMP			--3.  집계항목설정마스터
	DELETE FROM ABA121T	WHERE COMP_CODE = @NEW_COMP			--4.  시산표MASTER			(계정설정이 동일할 경우에만 그대로 사용할 수 있음.)
	DELETE FROM ABA130T	WHERE COMP_CODE = @NEW_COMP			--5.  집계항목설정상세	(계정설정이 동일할 경우에만 그대로 사용할 수 있음.)
	DELETE FROM ABA131T	WHERE COMP_CODE = @NEW_COMP			--6.  집계항목설정HIDDEN	(계정설정이 동일할 경우에만 그대로 사용할 수 있음.)
	DELETE FROM ABA150T	WHERE COMP_CODE = @NEW_COMP			--7.  통화코드

	DELETE FROM ABA160T	WHERE COMP_CODE = @NEW_COMP			--8.  결산마감정보

	DELETE FROM ABA200T	WHERE COMP_CODE = @NEW_COMP			--9.  관리항목마스터
	DELETE FROM ABA210T	WHERE COMP_CODE = @NEW_COMP			--10. 사용자관리항목상세
	DELETE FROM ABA400T	WHERE COMP_CODE = @NEW_COMP			--11. 계정코드정보


--2.  (ABA100T)회계기준설정	
	INSERT INTO ABA100T (
			COMP_CODE, BASE_CODE, SLIP_NUM1, SLIP_NUM2, PROD_ACCNT, CIRCUL_ACCNT, CONT_ACCNT, SELL_ACCNT
			, AMT_POINT, EXCHG_BASE, PEND_YN, RETURN_YN, SLIP_MSG, IWOL_DIVI_YN, SLIP_PRINT, PRINT_LINE
			, BUDG_PRO_BASE, BUDG_YN, BUDG_BASE, REPAY_BASE, REPAY_METHOD, REPAY_COMPUTE, SALE_BASE
			, SALE_METHOD, ASST_QTY_YN, ASST_PRICE_YN, TAX_BASE, BILL_DIV_CODE, APP_NUM, MATRL_YN, DEL_DATE
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	)
	SELECT  @NEW_COMP, BASE_CODE, SLIP_NUM1, SLIP_NUM2, PROD_ACCNT, CIRCUL_ACCNT, CONT_ACCNT, SELL_ACCNT
			, AMT_POINT, EXCHG_BASE, PEND_YN, RETURN_YN, SLIP_MSG, IWOL_DIVI_YN, SLIP_PRINT, PRINT_LINE
			, BUDG_PRO_BASE, BUDG_YN, BUDG_BASE, REPAY_BASE, REPAY_METHOD, REPAY_COMPUTE, SALE_BASE
			, SALE_METHOD, ASST_QTY_YN, ASST_PRICE_YN, TAX_BASE, BILL_DIV_CODE, APP_NUM, MATRL_YN, DEL_DATE
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	FROM ABA100T
	WHERE COMP_CODE = @OLD_COMP

--3.  (ABA120T)집계항목설정마스터
	INSERT INTO ABA120T (
			COMP_CODE, GUBUN, DIVI, SEQ, ACCNT_CD, ACCNT_NAME, ACCNT_NAME2, ACCNT_NAME3, START_ACCNT
			, END_ACCNT, ADD_ACCNT, DELETE_ACCNT, OPT_DIVI, RIGHT_LEFT, DIS_DIVI, KIND_DIVI
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	)
	SELECT  @NEW_COMP, GUBUN, DIVI, SEQ, ACCNT_CD, ACCNT_NAME, ACCNT_NAME2, ACCNT_NAME3, START_ACCNT
			, END_ACCNT, ADD_ACCNT, DELETE_ACCNT, OPT_DIVI, RIGHT_LEFT, DIS_DIVI, KIND_DIVI
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	FROM ABA120T
	WHERE COMP_CODE = @OLD_COMP

--4.  (ABA121T)시산표MASTER			(계정설정이 동일할 경우에만 그대로 사용할 수 있음.)
	INSERT INTO ABA121T (
			COMP_CODE, GUBUN, DIVI, SEQ, ACCNT, ACCNT_CD, ACCNT_NAME, ACCNT_NAME2, ACCNT_NAME3, OPT_DIVI, RIGHT_LEFT, DIS_DIVI
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	)
	SELECT  @NEW_COMP, GUBUN, DIVI, SEQ, ACCNT, ACCNT_CD, ACCNT_NAME, ACCNT_NAME2, ACCNT_NAME3, OPT_DIVI, RIGHT_LEFT, DIS_DIVI
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	FROM ABA121T
	WHERE COMP_CODE = @OLD_COMP

--5.  (ABA130T)집계항목설정상세	(계정설정이 동일할 경우에만 그대로 사용할 수 있음.)
	INSERT INTO ABA130T (
			COMP_CODE, GUBUN, DIVI, ACCNT_CD, ACCNT, CAL_TYPE, DR_CR, CAL_DIVI, REFER
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	)
	SELECT  @NEW_COMP, GUBUN, DIVI, ACCNT_CD, ACCNT, CAL_TYPE, DR_CR, CAL_DIVI, REFER
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	FROM ABA130T
	WHERE COMP_CODE = @OLD_COMP

--6.  (ABA131T)집계항목설정HIDDEN	(계정설정이 동일할 경우에만 그대로 사용할 수 있음.)
/*
	INSERT INTO ABA131T (
			COMP_CODE, AUTO_NUM, GUBUN, DIVI, ACCNT_CD, ACCNT, DR_CR, CAL_DIVI
			, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER, INSERT_DB_TIME
	)
	SELECT  @NEW_COMP, AUTO_NUM, GUBUN, DIVI, ACCNT_CD, ACCNT, DR_CR, CAL_DIVI
			, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER, INSERT_DB_TIME
	--select *
	FROM ABA131T
	WHERE COMP_CODE = @OLD_COMP
*/
--7.  (ABA150T)통화코드
	INSERT INTO ABA150T (
			COMP_CODE, MONEY_UNIT, STATE_NAME, STATE_CODE
			, INSERT_DB_USER, INSERT_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	)
	SELECT  @NEW_COMP, MONEY_UNIT, STATE_NAME, STATE_CODE
			, INSERT_DB_USER, INSERT_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	FROM ABA150T
	WHERE COMP_CODE = @OLD_COMP


--8.  (ABA160T)결산마감정보
	INSERT INTO ABA160T (
			COMP_CODE, CLOSE_DATE, EX_CLOSE_FG, GL_CLOSE_FG, EX_CLOSE_DATE, GL_CLOSE_DATE
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	)
	SELECT  @NEW_COMP, CLOSE_DATE, EX_CLOSE_FG, GL_CLOSE_FG, EX_CLOSE_DATE, GL_CLOSE_DATE
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	FROM ABA160T
	WHERE COMP_CODE = @OLD_COMP


--9.  (ABA200T)관리항목마스터
	INSERT INTO ABA200T (
			COMP_CODE, AC_CD, AC_NAME, DT_TYPE, DT_LEN, DT_POPUP, USE_YN, SYSTEM_YN
			, INSERT_DB_USER, INSERT_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	)
	SELECT  @NEW_COMP, AC_CD, AC_NAME, DT_TYPE, DT_LEN, DT_POPUP, USE_YN, SYSTEM_YN
			, INSERT_DB_USER, INSERT_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	FROM ABA200T
	WHERE COMP_CODE = @OLD_COMP

--10. (ABA210T)사용자관리항목상세
	INSERT INTO ABA210T (
			COMP_CODE, AC_CD, AC_DATA, AC_NAME, REF_CODE1, REF_CODE2
			, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER, INSERT_DB_TIME
	)
	SELECT  @NEW_COMP, AC_CD, AC_DATA, AC_NAME, REF_CODE1, REF_CODE2
			, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03, INSERT_DB_USER, INSERT_DB_TIME
	FROM ABA210T
	WHERE COMP_CODE = @OLD_COMP

--11. (ABA400T)계정코드정보
	INSERT INTO ABA400T (
			COMP_CODE, ACCNT, ACCNT_NAME, AC_FULL_NAME, ACCNT_NAME2, ACCNT_NAME3, AC_CODE1, AC_CODE2, AC_CODE3
			, AC_CODE4, AC_CODE5, AC_CODE6, DR_CTL1, DR_CTL2, DR_CTL3, DR_CTL4, DR_CTL5, DR_CTL6, CR_CTL1, CR_CTL2
			, CR_CTL3, CR_CTL4, CR_CTL5, CR_CTL6, BOOK_CODE1, BOOK_CODE2, ACCNT_SPEC, SPEC_DIVI, PROFIT_DIVI
			, PEND_YN, PEND_CODE, BUDG_YN, BUDGCTL_YN, BUDGCTL_SUM_UNIT, DR_FUND, CR_FUND, COST_DIVI, FOR_YN
			, ACCNT_DIVI, JAN_DIVI, GROUP_YN, AUTHO_DIVI, SLIP_SW, SYSTEM_YN, SUBJECT_DIVI, ACCNT_CD, DIRECT_DIVI
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	)
	SELECT  @NEW_COMP, ACCNT, ACCNT_NAME, AC_FULL_NAME, ACCNT_NAME2, ACCNT_NAME3, AC_CODE1, AC_CODE2, AC_CODE3
			, AC_CODE4, AC_CODE5, AC_CODE6, DR_CTL1, DR_CTL2, DR_CTL3, DR_CTL4, DR_CTL5, DR_CTL6, CR_CTL1, CR_CTL2
			, CR_CTL3, CR_CTL4, CR_CTL5, CR_CTL6, BOOK_CODE1, BOOK_CODE2, ACCNT_SPEC, SPEC_DIVI, PROFIT_DIVI
			, PEND_YN, PEND_CODE, BUDG_YN, BUDGCTL_YN, BUDGCTL_SUM_UNIT, DR_FUND, CR_FUND, COST_DIVI, FOR_YN
			, ACCNT_DIVI, JAN_DIVI, GROUP_YN, AUTHO_DIVI, SLIP_SW, SYSTEM_YN, SUBJECT_DIVI, ACCNT_CD, DIRECT_DIVI
			, INSERT_DB_USER, INSERT_DB_TIME, UPDATE_DB_USER, UPDATE_DB_TIME, TEMPC_01, TEMPC_02, TEMPC_03, TEMPN_01, TEMPN_02, TEMPN_03
	FROM ABA400T
	WHERE COMP_CODE = @OLD_COMP
--*/
	
/* ---------------------------------------------------------------------------------------
-- 인사급여
----------------------------------------------------------------------------------------*/
--/*
	DELETE FROM HAD100T	WHERE COMP_CODE = @NEW_COMP			-- 1.  세율기준표
	DELETE FROM HAD200T	WHERE COMP_CODE = @NEW_COMP			-- 2.  소득세액공제
	DELETE FROM HAD300T	WHERE COMP_CODE = @NEW_COMP			-- 3.  국민연금,건강보험요율등록
	DELETE FROM HBS010T	WHERE COMP_CODE = @NEW_COMP			-- 4.  계산식분류
	DELETE FROM HBS120T	WHERE COMP_CODE = @NEW_COMP			-- 5.  비과세근로소득코드등록
	DELETE FROM HBS130T	WHERE COMP_CODE = @NEW_COMP			-- 6.  원천징수이행상황 신고코드등록
	DELETE FROM HBS240T	WHERE COMP_CODE = @NEW_COMP			-- 7.  메일서버등록
	DELETE FROM HBS300T	WHERE COMP_CODE = @NEW_COMP			-- 8.  (HBS300T)지급/공제코드등록
	DELETE FROM HBS340T	WHERE COMP_CODE = @NEW_COMP			-- 9.  (HBS340T)년월차기준등록
	DELETE FROM HBS400T	WHERE COMP_CODE = @NEW_COMP			--10.  (HBS400T)급여관리기준등록
	DELETE FROM HBS800T	WHERE COMP_CODE = @NEW_COMP			--11.  (HBS800T)서류코드
	DELETE FROM HCD100T	WHERE COMP_CODE = @NEW_COMP			--12.  (HCD100T)사업,기타소득공통코드
	DELETE FROM HRT100T	WHERE COMP_CODE = @NEW_COMP			--13.  (HRT100T)퇴직소득공제등록

-- 1.(HAD100T)세율기준표
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HAD100T_TEMP'))
		DROP TABLE #HAD100T_TEMP
		
	SELECT *
	  INTO #HAD100T_TEMP
	  FROM HAD100T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HAD100T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HAD100T
	SELECT * FROM #HAD100T_TEMP

-- 2.(HAD200T)소득세액공제
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HAD200T_TEMP'))
		DROP TABLE #HAD200T_TEMP
		
	SELECT *
	  INTO #HAD200T_TEMP
	  FROM HAD200T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HAD200T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HAD200T
	SELECT * FROM #HAD200T_TEMP

-- 3.(HAD300T)국민연금,건강보험요율등록
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HAD300T_TEMP'))
		DROP TABLE #HAD300T_TEMP
		
	SELECT *
	  INTO #HAD300T_TEMP
	  FROM HAD300T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HAD300T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HAD300T
	SELECT * FROM #HAD300T_TEMP


-- 4.(HBS010T)계산식분류
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HBS010T_TEMP'))
		DROP TABLE #HBS010T_TEMP
		
	SELECT *
	  INTO #HBS010T_TEMP
	  FROM HBS010T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HBS010T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HBS010T
	SELECT * FROM #HBS010T_TEMP


-- 5.(HBS120T)비과세근로소득코드등록
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HBS120T_TEMP'))
		DROP TABLE #HBS120T_TEMP
		
	SELECT *
	  INTO #HBS120T_TEMP
	  FROM HBS120T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HBS120T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HBS120T
	SELECT * FROM #HBS120T_TEMP

-- 6.(HBS130T)원천징수이행상황 신고코드등록
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HBS130T_TEMP'))
		DROP TABLE #HBS130T_TEMP
		
	SELECT *
	  INTO #HBS130T_TEMP
	  FROM HBS130T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HBS130T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HBS130T
	SELECT * FROM #HBS130T_TEMP

-- 7.(HBS240T)메일서버등록
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HBS240T_TEMP'))
		DROP TABLE #HBS240T_TEMP
		
	SELECT *
	  INTO #HBS240T_TEMP
	  FROM HBS240T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HBS240T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HBS240T
	SELECT * FROM #HBS240T_TEMP


-- 8.(HBS300T)지급/공제코드등록
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HBS300T_TEMP'))
		DROP TABLE #HBS300T_TEMP
		
	SELECT *
	  INTO #HBS300T_TEMP
	  FROM HBS300T
	 WHERE COMP_CODE = @OLD_COMP
	   AND CODE_TYPE = '1'
	   AND WAGES_CODE = '100'
	 
	UPDATE #HBS300T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HBS300T
	SELECT * FROM #HBS300T_TEMP


-- 9.(HBS340T)년월차기준등록
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HBS340T_TEMP'))
		DROP TABLE #HBS340T_TEMP
		
	SELECT *
	  INTO #HBS340T_TEMP
	  FROM HBS340T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HBS340T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HBS340T
	SELECT * FROM #HBS340T_TEMP

--10.(HBS400T)급여관리기준등록
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HBS400T_TEMP'))
		DROP TABLE #HBS400T_TEMP
		
	SELECT *
	  INTO #HBS400T_TEMP
	  FROM HBS400T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HBS400T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HBS400T
	SELECT * FROM #HBS400T_TEMP

--11.(HBS800T)서류코드
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HBS800T_TEMP'))
		DROP TABLE #HBS800T_TEMP
		
	SELECT *
	  INTO #HBS800T_TEMP
	  FROM HBS800T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HBS800T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HBS800T
	SELECT * FROM #HBS800T_TEMP

--12.(HCD100T)사업,기타소득공통코드
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HCD100T_TEMP'))
		DROP TABLE #HCD100T_TEMP
		
	SELECT *
	  INTO #HCD100T_TEMP
	  FROM HCD100T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HCD100T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HCD100T
	SELECT * FROM #HCD100T_TEMP


--13.(HRT100T)퇴직소득공제등록
	IF EXISTS (SELECT TOP 1 1 FROM tempdb..sysobjects WHERE id=object_id('tempdb..#HRT100T_TEMP'))
		DROP TABLE #HRT100T_TEMP
		
	SELECT *
	  INTO #HRT100T_TEMP
	  FROM HRT100T
	 WHERE COMP_CODE = @OLD_COMP
	 
	UPDATE #HRT100T_TEMP SET COMP_CODE = @NEW_COMP

	INSERT INTO HRT100T
	SELECT * FROM #HRT100T_TEMP

--*/
------------------------------------------------------------------------------------------

END

/*
ROLLBACK

COMMIT

*/
