
ALTER TABLE CMD100T ALTER COLUMN DVRY_CUST_SEQ NVARCHAR(10) NULL;
ALTER TABLE CMD100T ALTER COLUMN PROCESS_TYPE NVARCHAR(10) NULL;



ALTER TABLE CMB200T ALTER COLUMN DVRY_CUST_SEQ NVARCHAR(10) NULL;
ALTER TABLE CMB200T ALTER COLUMN PROCESS_TYPE NVARCHAR(20) NULL;

ALTER TABLE CMB201T ALTER COLUMN DVRY_CUST_SEQ NVARCHAR(10) NULL;
ALTER TABLE CMB201T ALTER COLUMN PROCESS_TYPE NVARCHAR(20) NULL;


ALTER TABLE CMB100T ALTER COLUMN DVRY_CUST_SEQ NVARCHAR(10) NULL;
ALTER TABLE CMB100T ALTER COLUMN PROCESS_TYPE NVARCHAR(10) NULL;



ALTER TABLE CMB101T ALTER COLUMN DVRY_CUST_SEQ NVARCHAR(10) NULL;
ALTER TABLE CMB101T ALTER COLUMN PROCESS_TYPE NVARCHAR(10) NULL;