
  ALTER TABLE CMB200T ADD PURCHASE_AMT	NUMERIC(30,8) NULL DEFAULT 0
  ALTER TABLE CMB200T ADD MARGIN_AMT	NUMERIC(30,8) NULL DEFAULT 0
  ALTER TABLE CMB200T ADD MARGIN_RATE	NUMERIC(30,8) NULL DEFAULT 0
  ALTER TABLE CMB200T ADD SALES_PROJECTION	NUMERIC(5,2) NULL DEFAULT 0

  ALTER TABLE CMD100T ADD SALES_PROJECTION	NUMERIC(5,2) NULL DEFAULT 0
  
  ALTER TABLE CMB201T ADD PURCHASE_AMT	NUMERIC(30,8) NULL DEFAULT 0
  ALTER TABLE CMB201T ADD MARGIN_AMT	NUMERIC(30,8) NULL DEFAULT 0
  ALTER TABLE CMB201T ADD MARGIN_RATE	NUMERIC(30,8) NULL DEFAULT 0
  ALTER TABLE CMB201T ADD SALES_PROJECTION	NUMERIC(5,2) NULL DEFAULT 0