CREATE TABLE [uniLITE].[SOF112T](
	[_EXCEL_JOBID] [nvarchar](32) NOT NULL,
	[_EXCEL_ROWNUM] [int] NOT NULL,
	[_EXCEL_HAS_ERROR] [char](1) NULL,
	[_EXCEL_ERROR_MSG] [nvarchar](100) NULL,
	[ITEM_CODE] [nvarchar](20) NULL,
	[QTY] [numeric](30, 6) NULL,
 CONSTRAINT [PK_SOF112T] PRIMARY KEY CLUSTERED 
	(
		[_EXCEL_JOBID] ASC,
		[_EXCEL_ROWNUM] ASC
	)
) ON [PRIMARY]