USE [unilite5]
GO

/****** Object:  Table [uniLITE].[BSA320T]    Script Date: 09/10/2014 21:10:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [uniLITE].[BSA320T](
	[COMP_CODE] [nvarchar](8) NOT NULL,
	[PGM_ID] [nvarchar](30) NOT NULL,
	[PT_TITLENAME_USE] [nvarchar](1) NULL,
	[PT_TITLENAME] [nvarchar](100) NULL,
	[PT_COMPANY_USE] [nvarchar](1) NULL,
	[PT_SANCTION_USE] [nvarchar](1) NULL,
	[PT_PAGENUM_USE] [nvarchar](1) NULL,
	[PT_OUTPUTDATE_USE] [nvarchar](1) NULL,
	[PT_SAVEASPDF_USE] [nvarchar](1) NULL,
	[PT_SAVEASXLS_USE] [nvarchar](1) NULL,
	[PT_SAVEASDOC_USE] [nvarchar](1) NULL,
	[INSERT_DB_USER] [nvarchar](20) NOT NULL,
	[INSERT_DB_TIME] [smalldatetime] NOT NULL,
	[UPDATE_DB_USER] [nvarchar](20) NOT NULL,
	[UPDATE_DB_TIME] [smalldatetime] NOT NULL,
	[TEMPC_01] [nvarchar](30) NULL,
	[TEMPC_02] [nvarchar](30) NULL,
	[TEMPC_03] [nvarchar](30) NULL,
	[TEMPN_01] [numeric](30, 6) NULL,
	[TEMPN_02] [numeric](30, 6) NULL,
	[TEMPN_03] [numeric](30, 6) NULL,
 CONSTRAINT [BSA320T_IDX00] PRIMARY KEY CLUSTERED 
(
	[COMP_CODE] ASC,
	[PGM_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('MASTER') FOR [COMP_CODE]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('Y') FOR [PT_TITLENAME_USE]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('') FOR [PT_TITLENAME]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('Y') FOR [PT_COMPANY_USE]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('Y') FOR [PT_SANCTION_USE]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('Y') FOR [PT_PAGENUM_USE]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('Y') FOR [PT_OUTPUTDATE_USE]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('Y') FOR [PT_SAVEASPDF_USE]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('Y') FOR [PT_SAVEASXLS_USE]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('Y') FOR [PT_SAVEASDOC_USE]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('uniLITE') FOR [INSERT_DB_USER]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT (getdate()) FOR [INSERT_DB_TIME]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ('uniLITE') FOR [UPDATE_DB_USER]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT (getdate()) FOR [UPDATE_DB_TIME]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ((0)) FOR [TEMPN_01]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ((0)) FOR [TEMPN_02]
GO

ALTER TABLE [uniLITE].[BSA320T] ADD  DEFAULT ((0)) FOR [TEMPN_03]
GO

